DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS friend;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE friend (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  friendname TEXT NOT NULL,
  birthmonth INTEGER NOT NULL,
  birthday INTEGER NOT NULL,
  giftname TEXT NOT NULL
);