DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS friend;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE friend (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT,
  friendname TEXT NOT NULL,
  register_id INTEGER NOT NULL,
  age INTEGER NOT NULL,
  birthday DATE NOT NULL,
  giftname TEXT ,
  hobby TEXT ,
  FOREIGN KEY (register_id) REFERENCES user (id)
);